- hosts: adc

  vars:
    max_clients: 5

  remote_user: root
  gather_facts: False
  collections:
    - citrix.adc

  tasks:
    - name: blue red ansible servicegroup
      delegate_to: localhost
      citrix_adc_servicegroup: 
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"


        servicegroupname: blue_red_ansible_sg
        servicetype: HTTP
        servicemembers: 
          - ip: 192.168.3.81
            port: 80
          - ip: 192.168.3.83
            port: 80


    - name: blue red ansible lbvs
      delegate_to: localhost
      netscaler_lb_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"


        name: blue_red_ansible_lbvs
        servicetype: TCP 
        ipv46: 192.168.3.85 
        port: 80
        servicegroupbindings:
          - servicegroupname: blue_red_ansible_sg

    - name: Set cs vserver
      delegate_to: localhost
      citrix_adc_cs_vserver:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: "{{ validate_certs }}"


        name: blue_red_ansible_csvs
        ipv46: 192.168.3.112
        port: 8080
        servicetype: HTTP

        policybindings:
            targetlbvserver: blue_red_ansible_lbvs
